### ISSUE TITLE
Add async support to WP7 version using Microsoft.Bcl.Async

### ISSUE THREAD

**Issue by xperiandri** [cimbalino/Cimbalino-Phone-Toolkit#10]
Please, add corresponding async methods which available in WP8 version of Cimbalino by adding dependency to Microsoft.Bcl.Async.

**Comment by pedrolamas** [comment]
Truth be told, I have thought on doing that a couple of times already, though I didn't want to force WP7 devs to actually have to get yet another dependency...

**Comment by xperiandri** [comment]
Why not?
It is already released and everybody in a sound mind uses it.

**Comment by pedrolamas** [comment]
Well, you got a point there!! Does the Microsoft.Bcl.Async work in VS2010 also?

**Comment by pedrolamas** [comment]
Just confirmed and the package is **not** supported in VS2010... which can be an issue for devs still using that version to create WP7 apps! :\

**Comment by jeffwilcox** [comment]
I believe the only way for a multi-targeting framework to be useful going forward will be to support async. I can't imagine trying to share code between 7.1 + 8.0 phone apps + Windows Store without async right now!

It might be time to leave those 2010 users behind (or at least survey your user base to see how many there are!)

Thanks to NuGet versioning, it makes sense that you could rev a major version (or similar) in introducing this change - that way existing clients should be prompted before moving forward, etc. Just make sure to tag Git or have a release branch in case you decide to continue to bug fix the pre-async version.
