### ISSUE TITLE
Custom Background color for Messagebox

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#12]
It is possible to add?

**Comment by ghost** [comment]
Another useful thing can be field IsVisible. I just clicked twice on the button, which shows messagebox, and got exception.

**Comment by pedrolamas** [comment]
I'm not sure I'm following, what is this related to? Cimbalino WP Toolkit only has a MessageBoxService which is a service wrapper for the System.Windows.MessageBox class, and this class does not support additional properties like BackgroundColor.

**Comment by ghost** [comment]
Correct, it is about MessageBoxService.
Maybe it is possible to fill and add a texture to the background?

**Comment by pedrolamas** [comment]
No way to do it with the internal MessageBox class, for that you have to use the implementation from the Windows Phone Toolkit (http://phone.codeplex.com) or other, and create a separate custom service.

**Comment by ghost** [comment]
Got it, thanks.
