### ISSUE TITLE
[Minor] Update links

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#15]
Hi,

Just noticed a small issue: you have lots of links in a lots of places, which are forwaring to https://github.com/Cimbalino/Cimbalino-Phone-Toolkit/downloads
Though, it holds some outdated versions.

**Comment by pedrolamas** [comment]
GitHub has disabled the Downloads section, but they still maintain the old stuff in! But you're right, I have to remove all those links as they are now pointing to some really old stale stuff!
