### ISSUE TITLE
Xaml shows error, though works fine

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#23]
App is for WP 7.1, using Cimbalino 3.1.0.

Just noted this stuff: 
http://clip2net.com/s/5QFyF9

**Comment by pedrolamas** [comment]
What version of Visual Studio is this? Do you have any code refactoring tool installed in your Visual Studio? Something like Jetbrains Resharper or Telerik JustCode.

**Comment by ghost** [comment]
It is 2012 Pro, Update 3.
Yep, Resharper.

**Comment by pedrolamas** [comment]
Are you still seeing this issue? I've tried to reproduce it a couple of times, so far haven't been successful!

**Comment by ghost** [comment]
Yep, i have no idea, what they are depending on. I didnt see it during last several days, but today i got it again.
Can it be caused by adding x:Name="MainPivotAppBar"?

**Comment by pedrolamas** [comment]
I've seen this a couple of times, have to investigate further but I do think it has something to do with the generic collections that are in use and some sort of Resharper/VSDesigner incompatibility!

**Comment by pedrolamas** [comment]
I now know that this was related to old MVVMLight versions that bundled old `System.Windows.Interactivity.dll`, and should not appear with the most up to date versions.
