### ISSUE TITLE
Per-pivot item binding

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#24]
Actually, not an issue, just a reminder question.
Any updates on this field? 
http://stackoverflow.com/questions/15987564/cimbalino-appbar-pivot-with-usercontrols/15987678

Short reminder: while having MainPivot with UserControls as PivotItems, it would be nice to define appbar inside UserControls. Or, at least, inside of pivot item. But not in the main page itself.

**Comment by pedrolamas** [comment]
Not at the moment, truth be told this currently isn't a priority of mine, but I do see the point you're making here!

For the moment all the appbars have to be created in the main page; you can however have the AppBar buttons and menu items binding to the UserControl specific ViewModel!
