### ISSUE TITLE
Issue with AutoFocusBehavior

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#25]
Ok, this is serious.

I have a pivot with 2 pivotitems: textbox (TabIndex = 10) + passwordbox (TabIndex = 11) on first, textbox (TabIndex = 20)+ 2 passwordboxes (TabIndex = 21,22) on second.

When i'm changing pivot items, i'm also setting corresponding IsTabStop for all boxes to true/false.

However, when i'm at second pivot page, when i'm selecting first textbox and press Enter, it switches to passwordbox from pivot 1.

The only workaround i found so far is to set not IsTabStop, but IsEnabled. Though, i dont like it, because while starting transition between pivots, boxes are invisible.

I dont have enough time for now to make a demo right now, i'll make it closer to the end of this week.

**Comment by ghost** [comment]
Btw, vice versa is the same issue. When i'm on the 1 pivotItem, in passwordbox, when i'm pressing enter, passwordbox from the second page is selected.
If to press enter again, second passwordbox of second page is selected, though i'm still on the first page.

So, something is wrong with IsTabStop  While using IsEnabled, everything is ok (except the fact that during transition, boxes are invisible).

PS: i really like visual effect with moving box to camera view. I tried just to use PasswordBox.Focus(), it was focused, but it was behind the keyboard. If using your AutoFocusBehavior, camera also jumps to see the control - that's really nice.

**Comment by pedrolamas** [comment]
I've tryed the layout you mentioned with the specified `TabIndex` values and it seems to be working as expected (though it doesn't select the correct PivotItem, but that can be easily done with the events on the behavior)

Not sure I follow on the usage of `IsEnabled` and `IsTabStop` you're currently using, can you get me a sample app to simulate the problem?

**Comment by ghost** [comment]
I'm using pivot with 2 pivotItems. Each of them has TextBoxes and PasswordBoxes. 
If to disable boxes from non-visible pivot via IsEnabled, then it would be notable during transition (small blinking, "appearing" of boxes during moving to new pivot).

I'll try to make sample project. Lets assume this as closed.

**Comment by Nearga** [comment]
Btw, i understood what was the reason. This happens with Telerik's TextBoxes/PasswordBoxes.
