### ISSUE TITLE
Just another issue in the deadline day: phoneNumberChooserService got null exception

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#27]
Screenshot: http://clip2net.com/s/61VijK

Using it like:

private readonly IPhoneNumberChooserService phoneNumberChooserService;

And then define it as c-tor parameters.

What drives me crazy is that it worked several weeks ago, when i was implementing it.

**Comment by pedrolamas** [comment]
Now this one is quite weird... can you check the stacktrace and paste it here? Or use the code instead just for this service and see exactly where are you getting this!

Does this happen with Emulator or Device (or both) ?

**Comment by pedrolamas** [comment]
Haven't been able to reproduce issue, closing for now.
