### ISSUE TITLE
MarketplaceInformationService caches previous app version

### ISSUE THREAD

**Issue by ghost** [cimbalino/Cimbalino-Phone-Toolkit#28]
At the moment MarketplaceInformationService returns correct application version even there is no internet connection, but it was some time ago. Probably it is because of WebRequest aggresive cache on WP7, see http://stackoverflow.com/questions/4461610/wp7-httpwebrequest-without-caching for details.

**Comment by pedrolamas** [comment]
Never thought on this but you do make a very good point! I'll fix this for the next release of the toolkit, thanks.

**Comment by ghost** [comment]
Thanks! It's a bit confusing when you're trying to check what happens when device is disconnected (I expected some exception, or 0.0.0.0 version or smth. like this) but instead everything works fine. :)
