### ISSUE TITLE
DeviceInfo nuget package depends on main toolkit

### ISSUE THREAD

**Issue by ScottIsAFool** [cimbalino/Cimbalino-Phone-Toolkit#34]
Even though it doesn't actually need it, the dependency is there which prevents this package from being used in a background agent. If there is a dependency needed, surely it's with the Background package?

**Comment by pedrolamas** [comment]
Seems a reasonable request, I'll have to check but at this time I think you're correct!

**Comment by ScottIsAFool** [comment]
To be honest, i know its ok without the main toolkit as i add it manually to my background agent :)
