### ISSUE TITLE
SystemTrayService dependency property please

### ISSUE THREAD

**Issue by lolohouse** [cimbalino/Cimbalino-Phone-Toolkit#35]
Please, add property dependency for SystemTrayService for show/hide controls binding to isvisible, enable/disable controls if SystemTrayService is show.
Thanks

**Comment by pedrolamas** [comment]
The system tray and the `SystemTrayService` are simple objects and not `DependencyObject` and as such, cannot support binding.

You can change those properties directly in the service instance, so I'm not sure what you actually require here besides that... :\
