### ISSUE TITLE
Windows Phone 8 looses ability to do everything through Blend Designer

### ISSUE THREAD

**Issue by chobo2** [cimbalino/Cimbalino-Phone-Toolkit#36]
Hi
I was playing around with the Cimbalino app toolbar first in Windows phone 7 and then in Windows Phone 8. I noticed that Windows Phone 8 last some functionality 

![screenshot001](https://f.cloud.github.com/assets/321584/2167458/7e616eb4-9519-11e3-80d1-32423a6a833e.png)

The above screenshot is through Blend 2012 with a WP8 project.

![screenshot002](https://f.cloud.github.com/assets/321584/2167470/a7d6f890-9519-11e3-8854-a904b8c4b3dc.png)

Now the above is the same area but now a WP7 project. It can't find any of the behavior stuff.

I really like using the designer to do it. Would be great if this got fixed and worked again.

**Comment by pedrolamas** [comment]
Nice spot, I'm going to check what is happening here and get back to you once I have more info! :)

**Comment by chobo2** [comment]
Any luck?

**Comment by pedrolamas** [comment]
Have been without internet for the last 2 weeks, so haven't checked yet... I'll be doing so by this weekend for sure!

**Comment by jeffwilcox** [comment]
@PedroLamas hope it was a nice vacation!

**Comment by pedrolamas** [comment]
@jeffwilcox would be great if it was vacations, but unfortunately no: house move... :)

**Comment by chobo2** [comment]
Any progress on this?

**Comment by pedrolamas** [comment]
I do see the same result, but unfortunately at this time I'm not sure of why does this happen... I'm going to do some tests by replacing the generic collections with non-generic ones and see if this fixes the issue.

I'm inclined to consider this as another Blend issue... :\

**Comment by chobo2** [comment]
Sigh, I don't know why MS is abandoning Blend, it is such a good program yet Blend 2012 seems to have quite a few issues that previous versions did not.

**Comment by pedrolamas** [comment]
I'm not saying Microsoft is abandoning Blend, and I sincerely hope they aren't...

I've started work on Cimbalino vNext, which will be a lot more future ready (or so I hope!), and that's why I haven't dedicated enough on actually fixing this... sorry! :\

**Comment by chobo2** [comment]
I know you did not say they where Abandoning it, I am saying that. I don't know much about how Blend works but I am just seeing lots of stuff not working like it did in Expression Blend. For instance the Long List Selector I could use Blend to make my jumpstyle headers back in wp7(when it was part of the toolkit) but now it is part of WP8, I found I can't do that anymore. 

What is Cimbalino vNext?

**Comment by pedrolamas** [comment]
Cimbalino for WP8, WP8.1, and possibly Win8.1 and others... ;)

**Comment by chobo2** [comment]
It will have the same packages(features) as it does now but just not compatible with windows phone 7?

**Comment by pedrolamas** [comment]
Hopefully yes!

**Comment by chobo2** [comment]
Cool, Can't wait to see it!

**Comment by pedrolamas** [comment]
The new [Cimbalino Toolkit](https://github.com/Cimbalino/Cimbalino-Toolkit) has been available for a while now, so closing this! :)
