### ISSUE TITLE
Appbar doesn't change when theme is selected within the app

### ISSUE THREAD

**Issue by DVDPT** [cimbalino/Cimbalino-Phone-Toolkit#39]
If you change the app theme in runtime (e.g using Jeff Wilcox thememanager) the appbar behavior don't change to the new theme. I Implemented the following on my apps if you want to add it ;)

public class ThemeAwareApplicationBarBehavior : ApplicationBarBehavior
    {
        public ThemeAwareApplicationBarBehavior()
        {
        }

```
    protected override void OnAttached()
    {
        base.OnAttached();
        BackgroundColor = ApplicationResources.Instance.GetResource<SolidColorBrush>("PhoneChromeBrush").Color;
        ForegroundColor = ApplicationResources.Instance.GetResource<SolidColorBrush>("PhoneForegroundBrush").Color;
    }
}
```

**Comment by pedrolamas** [comment]
True, but neither `ApplicationBarBehavior` nor Jeff's `ThemeManager` were built thinking in communicating between them! :)

Solution at this moment is just setting the `ApplicationBarBehavior.BackgroundColor` and `ApplicationBarBehavior.ForegroundColor` manually, like in the following example:

https://github.com/PedroLamas/GDrive/blob/master/PedroLamas.GDrive.WP7/View/NewFolderPage.xaml
