### ISSUE TITLE
No Intellisense hint for a single appbar MenuItems

### ISSUE THREAD

**Issue by Nearga** [cimbalino/Cimbalino-Phone-Toolkit#41]
I have an appbar with a BarIconButton: 

```
<i:Interaction.Behaviors>
    <cimbalino:ApplicationBarBehavior
        BackgroundColor="{StaticResource MyAppBarBackgroundColor}" 
        ForegroundColor="{StaticResource MyAppBarForegroundColor}" 
        Opacity="0.99">

        <cimbalino:ApplicationBarIconButton 
            Text="Proceed"
            IconUri="/Resources/Icons/appbar.check.rest.png"
            Command="{Binding ProceedCommand}"
            IsEnabled="{Binding IsBusy, Converter={StaticResource BooleanInversedConverter}}"
            />

    </cimbalino:ApplicationBarBehavior>
</i:Interaction.Behaviors>
```

Now, i want to add a MenuItem there. I'm setting a cursor at the next line after ApplicationBarIconButton, start typing `<cimbalino` and Intellisense offers me 2 possibilities: 
- ApplicationBarMenuItem (after adding, highlights it with "invalid type: ApplicationBarItemBase is expected, actual is ApplicationBarMenuItem")
- ApplicationBarIconButton (which works fine, but i need MenuItem)

After some googling, i found a correct solution 

```
       <cimbalino:ApplicationBarBehavior.MenuItems>
            <cimbalino:ApplicationBarMenuItem>

            </cimbalino:ApplicationBarMenuItem>
        </cimbalino:ApplicationBarBehavior.MenuItems>
```

However, looking like this thing can be improved. 
I'm using a wp7 project with MSVS 2012 Pro.

**Comment by pedrolamas** [comment]
Seems to be working fine with my VS2012:

![image](https://cloud.githubusercontent.com/assets/85504/3268228/c1117a2e-f2d9-11e3-8445-404905307118.png)

Do you have your VS2012 updated with the latest Service Packs?

**Comment by pedrolamas** [comment]
Just remembered that this might be related to me having Resharper installed... bottom line is that if you have VS2012 fully updated and you see this issue, then I'm afraid it is in fact a Designer issue in VS2012... :\

**Comment by Nearga** [comment]
Yep, SP4. 
Probably, its a resharper issue.

**Comment by pedrolamas** [comment]
It may actually be, but given there is nothing I can actually do to improve/fix this situation, I'm closing this.
