### ISSUE TITLE
MarketplaceInformationService.WebRequestEndGetResponse throws System.Xml.XmlException

### ISSUE THREAD

**Issue by emaori** [cimbalino/Cimbalino-Phone-Toolkit#45]
Sometime this code throws an exception:

```
                var _informationService = new MarketplaceInformationService();
                var result = await _informationService.GetAppInformationAsync();
```

The exception message is: System.Xml.XmlException: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.

Unfortunately I am not able to reproduce this error but it happens to 28% of my users app

**Comment by pedrolamas** [comment]
This specific service does a web request expecting a response with XML, so the content should start with a `<` char.

Seeing `0x1f` mentioned on the error as being the start byte seemed familiar to me... and [gzip](http://www.onicos.com/staff/iz/formats/gzip.html) does use `0x1f 0x8b` as header!

So the only thing I could think of is some weird proxy/firewall that does something to the response so the phone doesn't properly g-unzip it automatically.

It's the first time I actually see something like this, but at this point I don't think there is any way of fixing it... :\
